########################################
##############REDIS접속정보##############
########################################
redis:
  - id: "r1"
    use: true
    type: "single"
    uri: ["127.0.0.1:1111"]
    timeout: 5000
    auth:
    workers: 0

  - id: "r2"
    use: false
    type: "cluster"
    uri: ["127.0.0.1:1111","127.0.0.2:1111","127.0.0.3:1111"]
    timeout: 5000
    auth:
    workers: 0